/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as StockRouteImport } from './routes/stock'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehouseManifestsRouteImport } from './routes/warehouse.manifests'
import { Route as WarehouseOrderIdRouteImport } from './routes/warehouse.$orderId'
import { Route as StockTransferRouteImport } from './routes/stock.transfer'
import { Route as StockReceiveRouteImport } from './routes/stock.receive'
import { Route as StockMovementsRouteImport } from './routes/stock.movements'
import { Route as StockAdjustRouteImport } from './routes/stock.adjust'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as FinanceOrderIdRouteImport } from './routes/finance.$orderId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as AdminWoocommerceRouteImport } from './routes/admin.woocommerce'
import { Route as AdminWarehousesRouteImport } from './routes/admin.warehouses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStocksRouteImport } from './routes/admin.stocks'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPlatformsRouteImport } from './routes/admin.platforms'
import { Route as AdminMigrationRouteImport } from './routes/admin.migration'
import { Route as AdminCouriersRouteImport } from './routes/admin.couriers'
import { Route as AdminBundlesRouteImport } from './routes/admin.bundles'
import { Route as OrdersOrderIdEditRouteImport } from './routes/orders.$orderId.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminMigrationReconciliationRouteImport } from './routes/admin.migration.reconciliation'
import { Route as ApiWoocommerceWebhooksStoreIdRouteImport } from './routes/api.woocommerce.webhooks.$storeId'
import { Route as AdminMigrationBatchesBatchIdRouteImport } from './routes/admin.migration.batches.$batchId'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseManifestsRoute = WarehouseManifestsRouteImport.update({
  id: '/manifests',
  path: '/manifests',
  getParentRoute: () => WarehouseRoute,
} as any)
const WarehouseOrderIdRoute = WarehouseOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => WarehouseRoute,
} as any)
const StockTransferRoute = StockTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => StockRoute,
} as any)
const StockReceiveRoute = StockReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => StockRoute,
} as any)
const StockMovementsRoute = StockMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => StockRoute,
} as any)
const StockAdjustRoute = StockAdjustRouteImport.update({
  id: '/adjust',
  path: '/adjust',
  getParentRoute: () => StockRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const FinanceOrderIdRoute = FinanceOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => FinanceRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const AdminWoocommerceRoute = AdminWoocommerceRouteImport.update({
  id: '/woocommerce',
  path: '/woocommerce',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWarehousesRoute = AdminWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformsRoute = AdminPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouriersRoute = AdminCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersOrderIdEditRoute = OrdersOrderIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrdersOrderIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrationReconciliationRoute =
  AdminMigrationReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AdminMigrationRoute,
  } as any)
const ApiWoocommerceWebhooksStoreIdRoute =
  ApiWoocommerceWebhooksStoreIdRouteImport.update({
    id: '/api/woocommerce/webhooks/$storeId',
    path: '/api/woocommerce/webhooks/$storeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMigrationBatchesBatchIdRoute =
  AdminMigrationBatchesBatchIdRouteImport.update({
    id: '/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => AdminMigrationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/migration': typeof AdminMigrationRouteWithChildren
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin/woocommerce': typeof AdminWoocommerceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/finance/$orderId': typeof FinanceOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/stock/adjust': typeof StockAdjustRoute
  '/stock/movements': typeof StockMovementsRoute
  '/stock/receive': typeof StockReceiveRoute
  '/stock/transfer': typeof StockTransferRoute
  '/warehouse/$orderId': typeof WarehouseOrderIdRoute
  '/warehouse/manifests': typeof WarehouseManifestsRoute
  '/admin/migration/reconciliation': typeof AdminMigrationReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/admin/migration/batches/$batchId': typeof AdminMigrationBatchesBatchIdRoute
  '/api/woocommerce/webhooks/$storeId': typeof ApiWoocommerceWebhooksStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/migration': typeof AdminMigrationRouteWithChildren
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin/woocommerce': typeof AdminWoocommerceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/finance/$orderId': typeof FinanceOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/stock/adjust': typeof StockAdjustRoute
  '/stock/movements': typeof StockMovementsRoute
  '/stock/receive': typeof StockReceiveRoute
  '/stock/transfer': typeof StockTransferRoute
  '/warehouse/$orderId': typeof WarehouseOrderIdRoute
  '/warehouse/manifests': typeof WarehouseManifestsRoute
  '/admin/migration/reconciliation': typeof AdminMigrationReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/admin/migration/batches/$batchId': typeof AdminMigrationBatchesBatchIdRoute
  '/api/woocommerce/webhooks/$storeId': typeof ApiWoocommerceWebhooksStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/migration': typeof AdminMigrationRouteWithChildren
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin/woocommerce': typeof AdminWoocommerceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/finance/$orderId': typeof FinanceOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/stock/adjust': typeof StockAdjustRoute
  '/stock/movements': typeof StockMovementsRoute
  '/stock/receive': typeof StockReceiveRoute
  '/stock/transfer': typeof StockTransferRoute
  '/warehouse/$orderId': typeof WarehouseOrderIdRoute
  '/warehouse/manifests': typeof WarehouseManifestsRoute
  '/admin/migration/reconciliation': typeof AdminMigrationReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/admin/migration/batches/$batchId': typeof AdminMigrationBatchesBatchIdRoute
  '/api/woocommerce/webhooks/$storeId': typeof ApiWoocommerceWebhooksStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/finance'
    | '/login'
    | '/logout'
    | '/orders'
    | '/stock'
    | '/unauthorized'
    | '/warehouse'
    | '/admin/bundles'
    | '/admin/couriers'
    | '/admin/migration'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/shipping'
    | '/admin/stocks'
    | '/admin/users'
    | '/admin/warehouses'
    | '/admin/woocommerce'
    | '/customers/$customerId'
    | '/finance/$orderId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/stock/adjust'
    | '/stock/movements'
    | '/stock/receive'
    | '/stock/transfer'
    | '/warehouse/$orderId'
    | '/warehouse/manifests'
    | '/admin/migration/reconciliation'
    | '/api/auth/$'
    | '/orders/$orderId/edit'
    | '/admin/migration/batches/$batchId'
    | '/api/woocommerce/webhooks/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customers'
    | '/finance'
    | '/login'
    | '/logout'
    | '/orders'
    | '/stock'
    | '/unauthorized'
    | '/warehouse'
    | '/admin/bundles'
    | '/admin/couriers'
    | '/admin/migration'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/shipping'
    | '/admin/stocks'
    | '/admin/users'
    | '/admin/warehouses'
    | '/admin/woocommerce'
    | '/customers/$customerId'
    | '/finance/$orderId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/stock/adjust'
    | '/stock/movements'
    | '/stock/receive'
    | '/stock/transfer'
    | '/warehouse/$orderId'
    | '/warehouse/manifests'
    | '/admin/migration/reconciliation'
    | '/api/auth/$'
    | '/orders/$orderId/edit'
    | '/admin/migration/batches/$batchId'
    | '/api/woocommerce/webhooks/$storeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customers'
    | '/finance'
    | '/login'
    | '/logout'
    | '/orders'
    | '/stock'
    | '/unauthorized'
    | '/warehouse'
    | '/admin/bundles'
    | '/admin/couriers'
    | '/admin/migration'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/shipping'
    | '/admin/stocks'
    | '/admin/users'
    | '/admin/warehouses'
    | '/admin/woocommerce'
    | '/customers/$customerId'
    | '/finance/$orderId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/stock/adjust'
    | '/stock/movements'
    | '/stock/receive'
    | '/stock/transfer'
    | '/warehouse/$orderId'
    | '/warehouse/manifests'
    | '/admin/migration/reconciliation'
    | '/api/auth/$'
    | '/orders/$orderId/edit'
    | '/admin/migration/batches/$batchId'
    | '/api/woocommerce/webhooks/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  StockRoute: typeof StockRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  WarehouseRoute: typeof WarehouseRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWoocommerceWebhooksStoreIdRoute: typeof ApiWoocommerceWebhooksStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/manifests': {
      id: '/warehouse/manifests'
      path: '/manifests'
      fullPath: '/warehouse/manifests'
      preLoaderRoute: typeof WarehouseManifestsRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/warehouse/$orderId': {
      id: '/warehouse/$orderId'
      path: '/$orderId'
      fullPath: '/warehouse/$orderId'
      preLoaderRoute: typeof WarehouseOrderIdRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/stock/transfer': {
      id: '/stock/transfer'
      path: '/transfer'
      fullPath: '/stock/transfer'
      preLoaderRoute: typeof StockTransferRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/receive': {
      id: '/stock/receive'
      path: '/receive'
      fullPath: '/stock/receive'
      preLoaderRoute: typeof StockReceiveRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/movements': {
      id: '/stock/movements'
      path: '/movements'
      fullPath: '/stock/movements'
      preLoaderRoute: typeof StockMovementsRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/adjust': {
      id: '/stock/adjust'
      path: '/adjust'
      fullPath: '/stock/adjust'
      preLoaderRoute: typeof StockAdjustRouteImport
      parentRoute: typeof StockRoute
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/finance/$orderId': {
      id: '/finance/$orderId'
      path: '/$orderId'
      fullPath: '/finance/$orderId'
      preLoaderRoute: typeof FinanceOrderIdRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/admin/woocommerce': {
      id: '/admin/woocommerce'
      path: '/woocommerce'
      fullPath: '/admin/woocommerce'
      preLoaderRoute: typeof AdminWoocommerceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/warehouses': {
      id: '/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AdminWarehousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stocks': {
      id: '/admin/stocks'
      path: '/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platforms': {
      id: '/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminPlatformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/couriers': {
      id: '/admin/couriers'
      path: '/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AdminCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$orderId/edit': {
      id: '/orders/$orderId/edit'
      path: '/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof OrdersOrderIdEditRouteImport
      parentRoute: typeof OrdersOrderIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migration/reconciliation': {
      id: '/admin/migration/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/migration/reconciliation'
      preLoaderRoute: typeof AdminMigrationReconciliationRouteImport
      parentRoute: typeof AdminMigrationRoute
    }
    '/api/woocommerce/webhooks/$storeId': {
      id: '/api/woocommerce/webhooks/$storeId'
      path: '/api/woocommerce/webhooks/$storeId'
      fullPath: '/api/woocommerce/webhooks/$storeId'
      preLoaderRoute: typeof ApiWoocommerceWebhooksStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migration/batches/$batchId': {
      id: '/admin/migration/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/admin/migration/batches/$batchId'
      preLoaderRoute: typeof AdminMigrationBatchesBatchIdRouteImport
      parentRoute: typeof AdminMigrationRoute
    }
  }
}

interface AdminMigrationRouteChildren {
  AdminMigrationReconciliationRoute: typeof AdminMigrationReconciliationRoute
  AdminMigrationBatchesBatchIdRoute: typeof AdminMigrationBatchesBatchIdRoute
}

const AdminMigrationRouteChildren: AdminMigrationRouteChildren = {
  AdminMigrationReconciliationRoute: AdminMigrationReconciliationRoute,
  AdminMigrationBatchesBatchIdRoute: AdminMigrationBatchesBatchIdRoute,
}

const AdminMigrationRouteWithChildren = AdminMigrationRoute._addFileChildren(
  AdminMigrationRouteChildren,
)

interface AdminRouteChildren {
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCouriersRoute: typeof AdminCouriersRoute
  AdminMigrationRoute: typeof AdminMigrationRouteWithChildren
  AdminPlatformsRoute: typeof AdminPlatformsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehousesRoute: typeof AdminWarehousesRoute
  AdminWoocommerceRoute: typeof AdminWoocommerceRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCouriersRoute: AdminCouriersRoute,
  AdminMigrationRoute: AdminMigrationRouteWithChildren,
  AdminPlatformsRoute: AdminPlatformsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehousesRoute: AdminWarehousesRoute,
  AdminWoocommerceRoute: AdminWoocommerceRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface FinanceRouteChildren {
  FinanceOrderIdRoute: typeof FinanceOrderIdRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceOrderIdRoute: FinanceOrderIdRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface OrdersOrderIdRouteChildren {
  OrdersOrderIdEditRoute: typeof OrdersOrderIdEditRoute
}

const OrdersOrderIdRouteChildren: OrdersOrderIdRouteChildren = {
  OrdersOrderIdEditRoute: OrdersOrderIdEditRoute,
}

const OrdersOrderIdRouteWithChildren = OrdersOrderIdRoute._addFileChildren(
  OrdersOrderIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRouteWithChildren
  OrdersNewRoute: typeof OrdersNewRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRouteWithChildren,
  OrdersNewRoute: OrdersNewRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface StockRouteChildren {
  StockAdjustRoute: typeof StockAdjustRoute
  StockMovementsRoute: typeof StockMovementsRoute
  StockReceiveRoute: typeof StockReceiveRoute
  StockTransferRoute: typeof StockTransferRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockAdjustRoute: StockAdjustRoute,
  StockMovementsRoute: StockMovementsRoute,
  StockReceiveRoute: StockReceiveRoute,
  StockTransferRoute: StockTransferRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

interface WarehouseRouteChildren {
  WarehouseOrderIdRoute: typeof WarehouseOrderIdRoute
  WarehouseManifestsRoute: typeof WarehouseManifestsRoute
}

const WarehouseRouteChildren: WarehouseRouteChildren = {
  WarehouseOrderIdRoute: WarehouseOrderIdRoute,
  WarehouseManifestsRoute: WarehouseManifestsRoute,
}

const WarehouseRouteWithChildren = WarehouseRoute._addFileChildren(
  WarehouseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OrdersRoute: OrdersRouteWithChildren,
  StockRoute: StockRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  WarehouseRoute: WarehouseRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWoocommerceWebhooksStoreIdRoute: ApiWoocommerceWebhooksStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
